### ISSUE TITLE
State of the art

### ISSUE THREAD

**Issue by Theosakamg** [ros2java/design#1]
Two implementation :
- base on **rclc design** : https://github.com/esteve/ros2_java
- base on **rclcpp design** : https://github.com/ros2java-alfred/ros2_java (similar to rosjava version 1)

_**rclcpp design** is base on **rclc design** implementation._

-----
Motivation of esteve version (rclc design) : https://github.com/esteve/ros2_java/issues/1#issuecomment-241872333
> I just made a first release of all code needed for writing Java and Android applications for ROS2, see https://groups.google.com/d/msg/ros-sig-ng-ros/y6m51E53Nyo/LTNUs9wADwAJ
> 
> I don't know if this may become the official implementation of Java for ROS2, it just happens to be the first one :-)
-----
Motivation of ros2java-alfred version (rclcpp design) :
> Object oriented implementation with same pattern than rclcpp  and rosjava (ROS1).

**Comment by Theosakamg** [comment]
@esteve propose to merge the two repository.

I'm ok (but i need to finish my implementation before, ~2weeks)

**Comment by esteve** [comment]
@Theosakamg there's really nothing in the current `ros2_java` that makes it less `rclcpp`, but what we could add is a wrapper on top of the current `ros2_java` to make it more similar to `rosjava`. However, to be honest, I already tried to make it as similar to `rosjava` as possible, but there are a couple of design decisions that can't be adapted to with the `rosjava` model.

Also, it's not accurate to say that `ros2_java` follows the `rclc` design. First because `rclc` does not exist, and second, because I myself wrote many parts of `rclcpp` :smile: I ported several of the design decisions of `rclcpp` to `ros2_java`.

**Comment by esteve** [comment]
@Theosakamg I think a good roadmap would be to add to https://github.com/esteve/ros2_java the improvements you've made, but in a consistent way. Right now the pull request you submitted contains too many changes, some of them are useful (e.g. the fixes to the generator) and some other are incorrect (e.g. the logging code).

Submitting self-contained pull requests makes it easier to understand and test the changes, and discuss any possible issues. For example, when I added support for services and clients (https://github.com/esteve/ros2_java/pull/6), I could have committed everything to the `master` branch, however I did it in a separate branch, so I could have a clearer picture of what the changes were. It also helped you to merge those changes into your fork, because they were isolated and clean, but if there where lots of commits, with leftover changes, etc. it would have made it more complicated for you to track https://github.com/esteve/ros2_java

**Comment by Theosakamg** [comment]
@esteve sorry for confusion...
I'm based on the https://github.com/ros2/rclc description it say "ROS Client Library for the C language."
and from https://github.com/ros2/rclcpp description it say "rclcpp (ROS Client Library for C++)"

My request is to use a namespace as rclcpp : 
- rclcpp::node::Node on https://github.com/ros2/rclcpp/blob/master/rclcpp/include/rclcpp/node.hpp
- rclcpp::parameter_service::ParameterService on https://github.com/ros2/rclcpp/blob/master/rclcpp/include/rclcpp/parameter_service.hpp

but with java syntax
- org.ros2.rcljava.node.Node on https://github.com/ros2java-alfred/ros2_java/blob/master/rcljava/src/main/java/org/ros2/rcljava/node/Node.java
- org.ros2.rcljava.node.parameter.ParameterService on https://github.com/ros2java-alfred/ros2_java/blob/master/rcljava/src/main/java/org/ros2/rcljava/node/parameter/ParameterService.java

inverse than rcl (in C language, all on root)
- rcl_node_t
- (not available now)

-------------

I make the split in many PR in 1 week (I need to finish the travis-ci docker image and porting to android of https://github.com/ros2java-alfred/ros2_java)

**Comment by esteve** [comment]
@Theosakamg if the only issue here is to move the classes to a separate namespace, I can do it right away in a second.

But I have to admit I'm a bit puzzled, you and @elehuitouze have been working on your own fork, it seems to me that a lot of duplication is going on, and it has diverged a lot from ros2_java. I don't understand what direction you're taking, especially since I announced this project just two months ago. So having a completely diverged and incompatible fork just two months after, feels strange at the least.

You guys have been working hard, but:

- you created your own incomplete Gradle plugin named org.ros2.rcljava (I think it'd be fair if you published it with a different name, to be honest). I already released one that worked for both Java and Android in October, but you keep pushing changes to yours instead of checking if mine works.
- forked the Travis repository I created, with your own Docker image
- assigned the copyright to yourselves

and to me, that's a lot of energy wasted. I keep asking you to contribute back, but I don't receive any response, so I wonder what's going on.

**Comment by Theosakamg** [comment]
@esteve, the main issue is the separate namespace ! (for Team of Alfred project)

The main target for me, is to validate the portability of Alfred project to ROS2. (FYI I working to this project on my free-time)

The roadmap was :
- Topics (pub/sub) :ok: 
- Service (client/server) :ok: 
- Parameters (~Dynamic_reconfigure) :ok: 
- Graph 10%
- CLI tools (ros2java_utils) :ok: (POC)
- Gradle stack :ok: (fresh)
- IC : 70%
- Consolidate Tests : 50%
- Source install all java stack :ok: (not publish)
- Script launch :ok: (not publish)
- Run/Test Alfred Java stack : 90%
- Run/Test Alfred Android stack : 40%

after that 
- Clean/Refactor the code
- PR (with separate PR :+1: )
- Propose to ROS2 core team to integrate java on main stack (dream)

I take a delay with docker image, but i keep the target.

**Comment by Theosakamg** [comment]
Update...
All Alfred stack java/Android was ported for ros2.

Now : clean/refactor the code

**Comment by Theosakamg** [comment]
_sorry for long time to response,
I closed the issue because the proof of concept is not completed_ 

I have a difficulty to integrate travis job for validate test. (to long to compile)
